package com.myspace.solar_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ElectricPermit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Permit Id")
	private String id;
	@org.kie.api.definition.type.Label("Permit Status")
	private java.lang.String status;

	public ElectricPermit() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public ElectricPermit(java.lang.String id, java.lang.String status) {
		this.id = id;
		this.status = status;
	}

}