package com.myspace.solar_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOAApprovalResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Is Approval Required")
	private java.lang.Boolean isApprovalRequired;

	public HOAApprovalResponse() {
	}

	public java.lang.Boolean getIsApprovalRequired() {
		return this.isApprovalRequired;
	}

	public void setIsApprovalRequired(java.lang.Boolean isApprovalRequired) {
		this.isApprovalRequired = isApprovalRequired;
	}

	public HOAApprovalResponse(java.lang.Boolean isApprovalRequired) {
		this.isApprovalRequired = isApprovalRequired;
	}

}