package com.myspace.solar_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HOAApprovalResponse implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HOAApprovalResponse() {
    }




}